apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.baseResourceName }}-servercert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.server_cert_crt | b64enc }}
  tls.key: {{ .Values.server_cert_key | b64enc }}
