apiVersion: v1
kind: Secret
metadata:
  name: opentelemetry-collector-config
stringData:
  opentelemetry-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: 
        timeout: 5s
      filter/drophttp:
        error_mode: ignore
        traces:
          span:
            - IsMatch(attributes["url.path"],"/check.*")
    exporters:
      nop:
      debug:
        verbosity: detailed
      kafka/traces:
        topic: MY_TOPIC
        encoding: jaeger_proto
        brokers: "broker1:9092,broker1:9092"
        protocol_version: 2.0.0
        auth:
          tls:
            cert_file: /certs/cert.pem
            key_file: /certs/key.pem
            ca_file: /certs/ca.pem
    extensions:
      health_check:
        endpoint: ":8080"
        path: "/health"
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch,filter/drophttp]
          exporters: [kafka/traces]
