apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-app1
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: 'false'
    nginx.ingress.kubernetes.io/auth-tls-secret: {{ .Values.global.namespace }}{{ "/" }}{{ .Chart.Name }}-ca-bundle
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'optional_no_ca'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '2'
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.global.hostname }}
    secretName: {{ .Chart.Name }}-servercert
  rules:
  - host: {{ .Values.global.hostname }}
    http:
      paths:
      - path: /{{ .Release.Name }}/app1
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-app1
            port:
              number: 443
