apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.baseResourceName }}-webapp
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.baseResourceName }}-webapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
