[SERVICE]
    Flush                   1
    Log_Level               ${LOG_LEVEL}
    Daemon                  off
    Parsers_File            parsers.conf
    #Plugins_file  plugins.conf
    #HTTP_Server   On
    #HTTP_Listen   0.0.0.0
    #HTTP_Port     ${METRICS_PORT}
    Health_Check            On

#@INCLUDE include-config/input*.conf # Add INPTUN.Name=tcp

[INPUT]
    Name                    tail
    Tag                     main
    Path                    ${APP_LOGS_PATH}
    Exclude_Path            ${APP_LOGS_EXCLUDE_PATH}
    Read_from_Head          true
    Inotify_Watcher         On
    Refresh_Interval        15

[FILTER]
    name                    multiline
    match                   *
    multiline.key_content   log
    multiline.parser        my_multiline

[FILTER]
    name                    parser
    match                   *
    key_name                log
    parser                  my_structure_extraction

[FILTER]
    Name                    lua
    Match                   *
    script                  scripts.lua
    call                    convert_time_field

#--------------------------------------------------
[FILTER]
    Name modify
    Match *
    Add envType K8S
    Add namespace ${POD_NAMESPACE}

[FILTER]
    Name modify
    Match *
    Condition Key_Does_Not_Exist podName
    Add podName ${POD_NAME}

#--------------------------------------------------
[OUTPUT]
    Name        kafka
    Match       main
    Topics      ${KAFKA_TOPICS}
    Brokers     ${KAFKA_BROKER}
    Format      ${OUTPUT_KAFKA_FORMAT}
    Retry_Limit ${OUTPUT_KAFKA_RETRY_LIMIT}
    queue_full_retries ${OUTPUT_KAFKA_QUEUE_FULL_RETRIES}
    rdkafka.message.timeout.ms ${OUTPUT_KAFKA_RDKAFKA_MESSAGE_TIMEOUT}
    rdkafka.queue.buffering.max.kbytes ${OUTPUT_KAFKA_RDKAFKA_QUEUE_BUFFERING_MAX_KBYTES}
    rdkafka.security.protocol ${OUTPUT_KAFKA_RDKAFKA_SECURITY_PROTOCOL}
    rdkafka.ssl.ca.location ${OUTPUT_KAFKA_RDKAFKA_SSL_CA_LOCATION}
    rdkafka.ssl.certificate.location ${OUTPUT_KAFKA_RDKAFKA_SSL_CERTIFICATE_LOCATION}
    rdkafka.ssl.key.location ${OUTPUT_KAFKA_RDKAFKA_KEY_LOCATION}
    rdkafka.ssl.key.password ${CLIENT_KAFKA_CERT_KEY_PASSWORD}
    rdkafka.enable.ssl.certificate.verification ${OUTPUT_KAFKA_RDKAFKA_ENABLE_SSL_CERTIFICATE_VERIFICATION}

#--------------------------------------------------
#"INPUT_TCP_LISTEN=127.0.0.1",
#"INPUT_PORT=5170",
#"INPUT_SECONDARY_PORT=",
#"INPUT_TCP_CHUNK_SIZE=27k",
#"INPUT_TCP_BUFFER_SIZE=972k",
#"INPUT_TCP_FORMAT=json",
#"INPUT_TCP_MEM_BUF_LIMIT=128MB",
#"KAFKA_BROKER=SET_EXTERNALLY",
#"KAFKA_TOPICS=SET_EXTERNALLY",
#"KAFKA_SECONDARY_TOPICS=",
#"OUTPUT_KAFKA_FORMAT=json",
#"OUTPUT_KAFKA_RETRY_LIMIT=false",
#"OUTPUT_KAFKA_QUEUE_FULL_RETRIES=0",
#"OUTPUT_KAFKA_RDKAFKA_MESSAGE_TIMEOUT=0",
#"OUTPUT_KAFKA_RDKAFKA_QUEUE_BUFFERING_MAX_KBYTES=20480",
#"OUTPUT_KAFKA_RDKAFKA_SECURITY_PROTOCOL=ssl",
#"OUTPUT_KAFKA_RDKAFKA_SSL_CA_LOCATION=/fluent-bit/etc/cert/ca-kafka-cert.pem",
#"OUTPUT_KAFKA_RDKAFKA_SSL_CERTIFICATE_LOCATION=/fluent-bit/etc/cert/client-kafka-cert.pem",
#"OUTPUT_KAFKA_RDKAFKA_KEY_LOCATION=/fluent-bit/etc/cert/client-kafka-cert-key.pem",
#"OUTPUT_KAFKA_RDKAFKA_ENABLE_SSL_CERTIFICATE_VERIFICATION=true",
#"METRICS_PORT=2020",
#"LOG_LEVEL=SET_EXTERNALLY",
#"ENV_TYPE="
#--------------------------------------------------
