[MULTILINE_PARSER]
    name            my_multiline
    type            regex
    flush_timeout   1000
    rule            "start_state" "/^(FATAL|ERROR|WARN|INFO|DEBUG|TRACE)\|(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\d{1}\|[\d\w|.]+(?::[\d\w|.]+)?:$/" "cont"
    rule            "cont"        "/^(?!(FATAL|ERROR|WARN|INFO|DEBUG|TRACE)\|(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\d{1}\|[\d\w|.]+(?::[\d\w|.]+)?:).*$/" "cont"

[PARSER]
    Name            my_structure_extraction
    Format          regex
    Regex           /^(?<level>FATAL|ERROR|WARN|INFO|DEBUG|TRACE)\|(?<localTime>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\d{1}\|(?<loggerName>[\d\w|.]+(?::[\d\w|.]+)?)\:\r?\n(?<text>(?:.|\r?\n)*[^\r\n]+)(?:\r?\n)?$/
    Time_Key        localTime
    Time_Format     %Y-%m-%d %H:%M:%S.%L
    Time_Keep       On
