apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-app2
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.sslredirect }}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Chart.Name }}-servercert
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /{{ .Release.Name }}/app2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-app2
            port:
              number: 80
