apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-configs
type: Opaque
data:
  app1_settings_json: {{ .Values.app1_settings_json | b64enc }}
  app2_settings_json: {{ .Values.app2_settings_json | b64enc }}