port 0
tls-port 6379
tls-replication yes
tls-auth-clients yes

tls-cert-file server.crt
tls-key-file server.key
tls-client-cert-file client.crt
tls-client-key-file client.key
tls-ca-cert-file ca.crt

enable-debug-command yes

replica-announce-ip $REDIS_HOST
replica-announce-port $REDIS_PORT

user default off
user x_client on >x_clientpass allchannels allkeys +@pubsub +@connection +@read +@write +@scripting -@admin -@dangerous +INFO +ROLE +CLUSTER|NODES +CONFIG|GET +TIME
user x_admin on >x_adminpass allchannels allkeys allcommands
user x_repl_to_master on >x_repl_to_master_pass +psync +replconf +ping
user x_sent_to_redis on >x_sent_to_redis_pass allchannels +multi +slaveof +ping +exec +subscribe +config|rewrite +role +publish +info +client|setname +client|kill +script|kill

masteruser x_repl_to_master
masterauth x_repl_to_master_pass
