port 0
tls-port 26379
tls-replication yes
tls-auth-clients yes

tls-cert-file server.crt
tls-key-file server.key
tls-client-cert-file client.crt
tls-client-key-file client.key
tls-ca-cert-file ca.crt

sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel announce-ip $SENTINEL_HOST
sentinel announce-port $SENTINEL_PORT

sentinel monitor $SENTINEL_MASTER_NAME $SENTINEL_MASTER_HOST $SENTINEL_MASTER_PORT $SENTINEL_QUORUM
sentinel down-after-milliseconds $SENTINEL_MASTER_NAME $SENTINEL_DOWN_AFTER
sentinel failover-timeout $SENTINEL_MASTER_NAME $SENTINEL_FAILOVER
sentinel parallel-syncs $SENTINEL_MASTER_NAME 1

sentinel auth-user $SENTINEL_MASTER_NAME x_sent_to_redis
sentinel auth-pass $SENTINEL_MASTER_NAME x_sent_to_redis_pass

user default off
user x_client on >x_clientpass allchannels +@pubsub +@connection -@admin -@dangerous +INFO +SENTINEL|MASTERS +SENTINEL|REPLICAS +SENTINEL|SENTINELS +SENTINEL|GET-MASTER-ADDR-BY-NAME
user x_admin on >x_adminpass allchannels allcommands
user x_sent_to_sent on >x_sent_to_sent_pass allchannels allcommands

sentinel sentinel-user x_sent_to_sent
sentinel sentinel-pass x_sent_to_sent_pass
